source source SHRP_DEVICE_CODE=umi
source SHRP_PATH=device/xiaomi/$(source SHRP_DEVICE_CODE)
source SHRP_MAINTAINER=PedroZ
source SHRP_REC_TYPE=MIUI
source SHRP_DEVICE_TYPE=A_Only
source SHRP_REC=</dev/block/bootdevice/by-name/recovery>
source SHRP_EDL_MODE=0
source SHRP_INTERNAL=/sdcard
source SHRP_EXTERNAL=/external_sd
source SHRP_OTG=/usb_otg
source SHRP_FLASH=1
source SHRP_STATUSBAR_RIGHT_PADDING=180
source SHRP_STATUSBAR_LEFT_PADDING=120
source SHRP_EXPRESS=true
source SHRP_EXPRESS_USE_DATA=true
source SHRP_DARK=true
source SHRP_CUSTOM_FLASHLIGHT=true
source SHRP_FONP_1=/sys/class/leds/led:torch_0/brightness
source SHRP_FONP_2=/sys/class/leds/led:torch_1/brightness
source SHRP_FONP_3=/sys/class/leds/led:switch/brightness
source SHRP_FLASH_MAX_BRIGHTNESS=200
source SHRP_SKIP_DEFAULT_ADDON_1=true
source SHRP_SKIP_DEFAULT_ADDON_2=true
source SHRP_SKIP_DEFAULT_ADDON_3=true
source SHRP_SKIP_DEFAULT_ADDON_4=true
source INC_IN_REC_MAGISK=true
